### ISSUE TITLE
Neo Compiler CSharp Feedbacks

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#498]
This issue is opened for all feedbacks for the new developed CSharp compiler. 

[ToBeAdded]

- [x]  #499 Support ByteString explicit cast for BigInteger type
- [x] #501 Support array foreach
- [x] #502 Support ToByteArray() overload
- [x] #503 Storage Find with RemovePrefix Option only remove One Byte
- [x] #521 Support Extended Method for type
- [x] #527 Check null should return
- [x] #539 nccs provides no error location information
- [x] #540 nccs doesn't pick up CS file from parent folder specified in .csproj file
- [x] #541 nccs can't compile contract w/ custom attribute on method
- [x] #549 nccs should accept multiple .cs files on the command line
- [ ] #550 nccs should support /reference command line option like csc.exe
- [x] #551 Create NccsTask for MSBuild
- [x] #560 Return help information when using nccs without any argument or option.

**Comment by devhawk** [comment]
Please add #539, #540 and #541

**Comment by devhawk** [comment]
@cloud8little I didn't realize that I could change your comment if I clicked on a check box! I accidently clicked on the #541, but I unclicked it.

**Comment by devhawk** [comment]
Please add #549, #550, #551

**Comment by devhawk** [comment]
#566

**Comment by devhawk** [comment]
Please add #574

**Comment by shargon** [comment]
Only https://github.com/neo-project/neo-devpack-dotnet/issues/550 left, I close this to follow in #550
